/**
 * This file and any referenced files were automatically generated by @osmonauts/telescope@0.73.1
 * DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
 * and run the transpile command or yarn proto command to regenerate this bundle.
 */

import * as _0 from "./bonds/genesis";
import * as _1 from "./bonds/bonds";
import * as _2 from "./bonds/query";
import * as _3 from "./bonds/tx";
import * as _3_1 from "./bonds/rpc.query";
import * as _3_2 from "./bonds/rpc.tx";

import * as _4 from "./cosmos/coin";
import * as _5 from "./cosmos/cosmos";
import * as _6 from "./cosmos/pagination";

import * as _7 from "./entity/entity";
import * as _8 from "./entity/genesis";
import * as _9 from "./entity/query";
import * as _10 from "./entity/tx";

import * as _11 from "./iid/event";
import * as _12 from "./iid/genesis";
import * as _13 from "./iid/iid";
import * as _14 from "./iid/query";
import * as _15 from "./iid/tx";

import * as _16 from "./legacy/did/did";
import * as _17 from "./legacy/did/diddoc";

import * as _18 from "./payments/genesis";
import * as _19 from "./payments/payments";
import * as _20 from "./payments/query";
import * as _21 from "./payments/tx";

import * as _22 from "./project/genesis";
import * as _23 from "./project/project";
import * as _24 from "./project/query";
import * as _25 from "./project/tx";

export namespace ixo {
  export const bonds = {
    ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._3_1,
    ..._3_2,
  };
  export const cosmos = {
    ..._4,
    ..._5,
    ..._6,
  };
  export const entity = {
    ..._7,
    ..._8,
    ..._9,
    ..._10,
  };
  export const iid = {
    ..._11,
    ..._12,
    ..._13,
    ..._14,
    ..._15,
  };
  export const did = {
    ..._16,
    ..._17,
  };
  export const payments = {
    ..._18,
    ..._19,
    ..._20,
    ..._21,
  };
  export const project = {
    ..._22,
    ..._23,
    ..._24,
    ..._25,
  };
}
